#FROM java:openjdk-8u111-jre
FROM java:openjdk-8-alpine
VOLUME /tmp
ADD eurekaserver-0.0.1-SNAPSHOT.jar app.jar
RUN sh -c 'touch /app.jar' \
    && echo "Asia/Shanghai" > /etc/timezone
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]
